name: AuctionMaster
author: qKing12
version: "3.2.3"
main: me.qKing12.AuctionMaster.AuctionMaster
description: A not so simple plugin for auctions.

api-version: "1.13"

softdepend: [CustomEconomy, Citizens, Vault, PlayerPoints, TokenManager, PlaceholderAPI, Skript, ProtocolLib, HeadDatabase]

commands:
  auction:
    aliases: [ah, auctions, auctionhouse, ahouse]
    description: Use this command to open the auction menu.
  ahview:
    description: View an auction.
  ahadmin:
    description: Use this command for admin things.